kedge <subcommand> errors out without -f/--files
Before this commit, running `kedge` subcommands without passing
any files would do nothing.

$ kedge deploy
$

$ kedge generate
$

$ kedge undeploy
$

This commit adds a check that input files are passed using -f or
--files flags, and if not, throws an error.

$ kedge generate
Error: Unable to validate input files: No files were passed. Please pass file(s) using '-f' or '--files'

The flags have also been marked as required, however, that takes
no effect, and there is an open issue on the spf13/cobra package
tracking the same - https://github.com/spf13/cobra/issues/206

Fixes #96